/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TradeList: typeof import('./components/tradeList.vue')['default']
    TradeOverview: typeof import('./components/tradeOverview.vue')['default']
    TransactionSummary: typeof import('./components/TransactionSummary.vue')['default']
    TransactionTable: typeof import('./components/TransactionTable.vue')['default']
  }
}
